# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-06 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_movie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
