# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=300, upload_to='images')),
                ('url', models.URLField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
