# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-06 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='电影名')),
                ('desc', models.CharField(max_length=300, verbose_name='电影描述')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('to_star', models.CharField(max_length=100, verbose_name='主演')),
                ('category', models.CharField(max_length=100, verbose_name='类型')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('image', models.ImageField(max_length=300, upload_to='images', verbose_name='封面图')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': 'images',
            },
        ),
    ]
