# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-06 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_movie_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie_detail',
            options={},
        ),
    ]
