# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-06 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190306_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名')),
                ('movie_nums', models.IntegerField(default=0, verbose_name='电影数量')),
            ],
        ),
        migrations.AlterField(
            model_name='movie_detail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Category', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='movie_detail',
            name='desc',
            field=models.TextField(verbose_name='电影描述'),
        ),
    ]
