# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-06 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190306_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_detail',
            name='image',
            field=models.ImageField(max_length=300, upload_to='static/images', verbose_name='封面图'),
        ),
    ]
